DROP TABLE IF EXISTS STUDENT_COURSE;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
    ID INTEGER NOT NULL, 
    NAME VARCHAR(255), 
    PRIMARY KEY (ID)
);
CREATE TABLE COURSE (
    ID INTEGER NOT NULL, 
    C_CODE VARCHAR(20),
    DESCRIPTION VARCHAR(150),
    PRIMARY KEY (ID)
);
CREATE TABLE STUDENT (
    ID INTEGER NOT NULL, 
    NAME VARCHAR(255), 
    MATRIC_NO VARCHAR(50),
    CAP DOUBLE NULL,
    DEPARTMENT_ID INTEGER, 
    PRIMARY KEY (ID)
);
CREATE TABLE STUDENT_COURSE (
    STUDENT_ID INTEGER NOT NULL,
    COURSE_ID INTEGER NOT NULL, 
    PRIMARY KEY (STUDENT_ID, COURSE_ID)
);
